// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuCXvWWDWvJAhCGJowDiT7bIPYI_MfIyY',
    appId: '1:67773570691:web:c5a37d25f4f657105985b6',
    messagingSenderId: '67773570691',
    projectId: 'movie-app-3101',
    authDomain: 'movie-app-3101.firebaseapp.com',
    storageBucket: 'movie-app-3101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb51hRZ_cpFqe1jOLEP2Hg3frYEVRqwBg',
    appId: '1:67773570691:android:aae7d1c5edd42a995985b6',
    messagingSenderId: '67773570691',
    projectId: 'movie-app-3101',
    storageBucket: 'movie-app-3101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV89KzVbY3_gsCO4FtGbgR00QOt77cRH4',
    appId: '1:67773570691:ios:1f29899867948b8c5985b6',
    messagingSenderId: '67773570691',
    projectId: 'movie-app-3101',
    storageBucket: 'movie-app-3101.appspot.com',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV89KzVbY3_gsCO4FtGbgR00QOt77cRH4',
    appId: '1:67773570691:ios:1f29899867948b8c5985b6',
    messagingSenderId: '67773570691',
    projectId: 'movie-app-3101',
    storageBucket: 'movie-app-3101.appspot.com',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuCXvWWDWvJAhCGJowDiT7bIPYI_MfIyY',
    appId: '1:67773570691:web:8f71a793e6b883e75985b6',
    messagingSenderId: '67773570691',
    projectId: 'movie-app-3101',
    authDomain: 'movie-app-3101.firebaseapp.com',
    storageBucket: 'movie-app-3101.appspot.com',
  );
}
